<?php

return [
    'positive_messages' => [
        "Your vibe is purely main character energy, straight out of a Bollywood movie.",
        "You're the friend everyone calls when the Goa plan is actually happening.",
        "You have that rare 'Desi aunties secretly approve' aura.",
        "Your resilience is stronger than an Indian mom’s Tupperware.",
        "You bring more joy than finding extra masala in a Maggi packet.",
        "Your aesthetic is unmatched, purely Pinterest board material.",
        "You have a natural ability to diffuse any family drama.",
        "Your hustle is inspiring—total CEO mindset.",
        "You carry yourself with the grace of a 90s indie pop song.",
        "Your intuition is sharper than a neighborhood gossip's radar.",
        "You bring absolute peace and clarity to your chaotic friend group.",
        "Your kindness ripples out further than you know.",
        "You have an undeniable aura of confidence, pure main energy.",
        "Your laughter is literal serotonin; it heals.",
        "You're a magnet for good opportunities and good food.",
        "You handle challenges like a pro—unfazed and focused.",
        "You have a rare, beautiful, and slightly unhinged mind.",
        "Your ability to adapt to any vibe is your literal superpower.",
        "You radiate positivity and zero toxic traits.",
        "Your loyalty makes you an unforgettable friend."
    ],
    'personality_types' => [
        "The Goa-Trip Planner",
        "The Midnight Maggi Chef",
        "The Unproblematic Observer",
        "The Group Chat Admin",
        "The Chai Connoisseur",
        "The Overthinking Philosopher",
        "The Aesthetic Nomad",
        "The Bollywood Main Character",
        "The Secret Hustler",
        "The Chill Backbencher",
        "The Serial Binge-Watcher",
        "The Spontaneous Explorer",
        "The Therapist Friend",
        "The Reel Scroller",
        "The Foodie Critic",
        "The Silent Overachiever",
        "The Late Night Deep-Talker",
        "The Festive Enthusiast",
        "The Sarcastic Introvert",
        "The Vibe Curator"
    ],
    'action_hints' => [
        "Stop overthinking and just send that text.",
        "Manifest that dream, but maybe also start working on it.",
        "Drink a glass of water, fix your posture, and call your mom.",
        "Your next big breakthrough is hiding in a hot cup of chai.",
        "Buy that outfit you've been sitting on in your Myntra cart.",
        "Say yes to the next random street food plan.",
        "Take a break from scrolling reels and touch some grass.",
        "Let go of that situationship; you deserve better.",
        "Speak your truth, even if it causes a little drama.",
        "Invest some time in learning that new skill you saved.",
        "Take a different, scenic route home today.",
        "Write down your thoughts before your overthinking spirals.",
        "Give out three genuine compliments today.",
        "Spend 10 minutes simply doing nothing. Just breathe.",
        "Ask for help with that thing you're silently struggling with.",
        "Celebrate your small wins more loudly—treat yourself.",
        "Declutter your room; it's a mess and you know it.",
        "Trust your gut feeling about that sketchy plan.",
        "Make time for your favorite hobby this long weekend.",
        "Be patient with yourself; you're doing absolutely great."
    ],
    'match_messages' => [
        "Total Rab Ne Bana Di Jodi vibes.",
        "You two balance each other out perfectly, like Chai and Parle-G.",
        "The energy between you is totally magnetic. Elite pairing.",
        "A match made in the stars—literally, your Kundlis align perfectly.",
        "You bring out the absolutely best in one another.",
        "Pure twin flame energy right here. Unstoppable.",
        "A slightly chaotic but absolutely perfect combination.",
        "You understand each other without speaking a single word.",
        "Total power couple potential. Watch out world.",
        "You provide the peace the other desperately needs."
    ]
];
